trigger:
  branches:
    include:
      - main
 
pool:
  vmImage: 'ubuntu-latest'
 
variables:
  AZURE_SQL_CONNECTION_STRING: 'astha-db.mysql.database.azure.com'
 
steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.x'
 
- script: |
    pip install mysql-connector-python
  displayName: 'Install MySQL Connector'
 
- script: |
    python -c "
    import mysql.connector;
    conn = mysql.connector.connect(host='astha-db.mysql.database.azure.com',
    user='root_astha',
    password='Secret55',
    database='assignment4db');
    cursor = conn.cursor();
    with open('create_table.sql', 'r') as file:
        cursor.execute(file.read());
    conn.close();
    "
  displayName: 'Run create_table.sql'
 
- script: |
    python -c "
    import mysql.connector;
    conn = mysql.connector.connect(host='astha-db.mysql.database.azure.com',
    user='root_astha',
    password='Secret55',
    database='assignment4db');
    cursor = conn.cursor();
    with open('update_table.sql', 'r') as file:
        cursor.execute(file.read());
    conn.close();
    "
  displayName: 'Run update_table.sql'
 
- script: |
    python -c "
    import mysql.connector;
    conn = mysql.connector.connect(host='astha-db.mysql.database.azure.com',
    user='root_astha',
    password='Secret55',
    database='assignment4db');
    cursor = conn.cursor();
    cursor.execute(\"SELECT COLUMN_NAME FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Users' AND COLUMN_NAME = 'Contact';\");
    result = cursor.fetchone();
    if result:
        print('Column exists: Validation successful.');
    else:
        raise Exception('Validation failed: Column does not exist.');
    conn.close();
    "
  displayName: 'Validate schema update'
has context menu